on:
  push:
    branches:
      - main
      - login-gcr.io

jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-22.04
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      # checkout code
      - uses: actions/checkout@v4

      # authenticate with GCP using serviceaccount
      - uses: 'google-github-actions/auth@v2'
        id: auth
        name: Authenticate to GCP
        with:
          project_id: 'cc-fall2024'
          workload_identity_provider: 'projects/584694283094/locations/global/workloadIdentityPools/github2/providers/dansc0de' # update with your Workload Identity Pool
          # service_account: 'github-actions@cc-fall2024.iam.gserviceaccount.com' # update with your ServiceAccount
      - run: gcloud auth configure-docker us-central1-docker.pkg.dev/cc-fall2024/node-demo
      # login to GCR
#      - uses: docker/login-action@v3
#        with:
#          registry: gcr.io
#          username: oauth2accesstoken
#          password: ${{ steps.auth.outputs.auth_token }}

